#load libraries
library(here)
source(here("scripts", "libs.R"))

#load both dataframes

data <- read_csv(here("data_raw", "M1Dur.csv"))
data2 <- read_csv(here("data_raw", "M1Int.csv"))


#find the means of all the fix1 and fix2 interval durations; these will be used
#to create multipliers for normalization

fix_1 <- data %>%
  filter(., TextGridLabel == "fix1") %>% 
  summarize(., mean = mean(duration)) %>%
  pull(.)

fix_2 <- data %>%                                                             
  filter(., TextGridLabel == "fix2") %>% 
  summarize(., mean = mean(duration)) %>%
  pull(.)

#long pipe for the dataframe; several things to accomplish
#   step 1: create multipliers for fix1 and fix2 that will correspond to fixes in each file.
#           it will only be calculated for the desired durations; all others fill to NA
#   step 2: fill in empty values in the multipliers column; multiplier1 fills down, m2 fills up
#   step 3: create a column for normalized duration; which multiplier the value multiplies by
#           is determined by the number at the end of the TextGridLabel
#   step 4: create a "Vowel" variable
#   step 5: create a "Stress" variable
#   step 6: create a "Multiplier" variable
#   step 7: create a "Word" variable
#   step 8: create a "Segment" variable
#   step 9: create a "Frame" variable
#   step 10: create a "Syllnum" variable
#   step 11: change f0_midpoint to a double (it was loaded as a character vector)

data_final <- data %>%   
  mutate(., multiplier1 = if_else(.$TextGridLabel=="fix1",                     #step 1a
                                  fix_1 / duration, as.double(NA))) %>%      
  fill(., multiplier1) %>%                                                     #step 2a
  mutate(., multiplier2 = if_else(.$TextGridLabel=="fix2",                     #step 1b
                                  fix_2 / duration, as.double(NA))) %>%             
  fill(., multiplier2, .direction = "up") %>%                                  #step 2b
  filter(., TextGridLabel != "fix1", TextGridLabel != "fix2") %>%
  mutate(., NormalizedDuration = case_when(                                    #step 3
    str_detect(.$TextGridLabel, "1$") ~ duration * multiplier1,
    str_detect(.$TextGridLabel, "10$") ~ duration * multiplier1,
    str_detect(.$TextGridLabel, "2$") ~ duration * multiplier1,
    str_detect(.$TextGridLabel, "20$") ~ duration * multiplier1,
    str_detect(.$TextGridLabel, "3$") ~ duration * multiplier1,
    str_detect(.$TextGridLabel, "30$") ~ duration * multiplier1,
    str_detect(.$TextGridLabel, "00$") ~ duration * multiplier2,
    str_detect(.$TextGridLabel, "4$") ~ duration * multiplier2,
    str_detect(.$TextGridLabel, "40$") ~ duration * multiplier2,
    str_detect(.$TextGridLabel, "5$") ~ duration * multiplier2,
    str_detect(.$TextGridLabel, "50$") ~ duration * multiplier2,
    str_detect(.$TextGridLabel, "6$") ~ duration * multiplier2,
    str_detect(.$TextGridLabel, "60$") ~ duration * multiplier2,
    str_detect(.$TextGridLabel, "0$") ~ duration * multiplier1
  )) %>%
  select(., Filename, TextGridLabel, NormalizedDuration, F1_midpoint, F2_midpoint, f0_midpoint) %>%
  mutate(., Vowel = case_when(                                                 #step 4
    str_detect(.$TextGridLabel, "^a") ~ "a",
    str_detect(.$TextGridLabel, "^e") ~ "e",
    str_detect(.$TextGridLabel, "^E") ~ "e",
    str_detect(.$TextGridLabel, "^i") ~ "i",
    str_detect(.$TextGridLabel, "^I") ~ "i",
    str_detect(.$TextGridLabel, "^o") ~ "o",
    str_detect(.$TextGridLabel, "^u") ~ "u",
    str_detect(.$TextGridLabel, "^U") ~ "u",
    str_detect(.$TextGridLabel, "^y") ~ "y"
  )) %>%
  mutate(., Stress = case_when(                                                #step 5
    str_detect(.$TextGridLabel, "^a") ~ "N",
    str_detect(.$TextGridLabel, "^e") ~ "N",
    str_detect(.$TextGridLabel, "^E") ~ "Y",
    str_detect(.$TextGridLabel, "^i") ~ "N",
    str_detect(.$TextGridLabel, "^I") ~ "Y",
    str_detect(.$TextGridLabel, "^o") ~ "N",
    str_detect(.$TextGridLabel, "^u") ~ "N",
    str_detect(.$TextGridLabel, "^U") ~ "Y",
    str_detect(.$TextGridLabel, "^y") ~ "N"
  )) %>%
  mutate(., Repetition = case_when(                                            #step 6  
    str_detect(.$Filename, "^M1A") ~ "1",
    str_detect(.$Filename, "^M1B") ~ "2",
    str_detect(.$Filename, "^M1C") ~ "3"
  )) %>%
  mutate(., Word = case_when(                                                  #step 7
    str_detect(.$Filename, "M1A6") ~ "palikimu",
    str_detect(.$Filename, "M1A7") ~ "palikimu",
    str_detect(.$Filename, "M1A8") ~ "cepelinu",
    str_detect(.$Filename, "M1A9") ~ "kalakutas",
    str_detect(.$Filename, "M1A10") ~ "katuko",
    str_detect(.$Filename, "M1A11") ~ "cepelinas",
    str_detect(.$Filename, "M1A12") ~ "deguto",
    str_detect(.$Filename, "M1A14") ~ "mygtukus",
    str_detect(.$Filename, "M1A15") ~ "tylumo",
    str_detect(.$Filename, "M1A16") ~ "apetitu",
    str_detect(.$Filename, "M1A17") ~ "kalakuto",
    str_detect(.$Filename, "M1A18") ~ "ratukus",
    str_detect(.$Filename, "M1A19") ~ "paketas",
    str_detect(.$Filename, "M1A20") ~ "remimo",
    str_detect(.$Filename, "M1A22") ~ "degutu",
    str_detect(.$Filename, "M1A23") ~ "mygtuko",
    str_detect(.$Filename, "M1A24") ~ "katukus",
    str_detect(.$Filename, "M1A25") ~ "degutas",
    str_detect(.$Filename, "M1A26") ~ "palikimus",
    str_detect(.$Filename, "M1A27") ~ "senumo",
    str_detect(.$Filename, "M1A29") ~ "malonumas",
    str_detect(.$Filename, "M1A30") ~ "lupiku",
    str_detect(.$Filename, "M1A31") ~ "paketus",
    str_detect(.$Filename, "M1A32") ~ "lupikas",
    str_detect(.$Filename, "M1A33") ~ "cepelinus",
    str_detect(.$Filename, "M1A34") ~ "paketu",
    str_detect(.$Filename, "M1A36") ~ "remimus",
    str_detect(.$Filename, "M1A37") ~ "palikimo",
    str_detect(.$Filename, "M1A38") ~ "kalakutus",
    str_detect(.$Filename, "M1A39") ~ "cepelino",
    str_detect(.$Filename, "M1A40") ~ "senumas",
    str_detect(.$Filename, "M1A41") ~ "ridiko",
    str_detect(.$Filename, "M1A43") ~ "palikimas",
    str_detect(.$Filename, "M1A44") ~ "malonumu",
    str_detect(.$Filename, "M1A45") ~ "gynimus",
    str_detect(.$Filename, "M1A46") ~ "paketo",
    str_detect(.$Filename, "M1A47") ~ "degutus",
    str_detect(.$Filename, "M1A48") ~ "tylumu",
    str_detect(.$Filename, "M1A51") ~ "senumus",
    str_detect(.$Filename, "M1A52") ~ "gynimas",
    str_detect(.$Filename, "M1A53") ~ "kalakutu",
    str_detect(.$Filename, "M1A54") ~ "apetitus",
    str_detect(.$Filename, "M1A55") ~ "remimu",
    str_detect(.$Filename, "M1A56") ~ "ridikas",
    str_detect(.$Filename, "M1A58") ~ "mygtuku",
    str_detect(.$Filename, "M1A59") ~ "apetitas",
    str_detect(.$Filename, "M1A60") ~ "tylumus",
    str_detect(.$Filename, "M1A61") ~ "gynimo",
    str_detect(.$Filename, "M1A62") ~ "malonumus",
    str_detect(.$Filename, "M1A63") ~ "lupikus",
    str_detect(.$Filename, "M1A65") ~ "malonumo",
    str_detect(.$Filename, "M1A66") ~ "katuku",
    str_detect(.$Filename, "M1A67") ~ "ratuko",
    str_detect(.$Filename, "M1A68") ~ "mygtukas",
    str_detect(.$Filename, "M1A69") ~ "ridiku",
    str_detect(.$Filename, "M1A70") ~ "tylumas",
    str_detect(.$Filename, "M1A72") ~ "gynimu",
    str_detect(.$Filename, "M1A73") ~ "katukas",
    str_detect(.$Filename, "M1A74") ~ "ratuku",
    str_detect(.$Filename, "M1A75") ~ "ridikus",
    str_detect(.$Filename, "M1A76") ~ "senumu",
    str_detect(.$Filename, "M1A77") ~ "apetito",
    str_detect(.$Filename, "M1A78") ~ "remimas",
    str_detect(.$Filename, "M1B6") ~ "apetitas",
    str_detect(.$Filename, "M1B7") ~ "degute",
    str_detect(.$Filename, "M1B8") ~ "lupikas",
    str_detect(.$Filename, "M1B10") ~ "cepeline",
    str_detect(.$Filename, "M1B11") ~ "ridikas",
    str_detect(.$Filename, "M1B14") ~ "senume",
    str_detect(.$Filename, "M1B15") ~ "lupiko",
    str_detect(.$Filename, "M1B16") ~ "katukus",
    str_detect(.$Filename, "M1B17") ~ "pakete",
    str_detect(.$Filename, "M1B18") ~ "lupikus",
    str_detect(.$Filename, "M1B19") ~ "katukas",
    str_detect(.$Filename, "M1B20") ~ "degutus",
    str_detect(.$Filename, "M1B23") ~ "ridikus",
    str_detect(.$Filename, "M1B24") ~ "ratuko",
    str_detect(.$Filename, "M1B25") ~ "mygtukus",
    str_detect(.$Filename, "M1B26") ~ "katuke",
    str_detect(.$Filename, "M1B27") ~ "ratukas",
    str_detect(.$Filename, "M1B29") ~ "apetito",
    str_detect(.$Filename, "M1B30") ~ "mygtuke",
    str_detect(.$Filename, "M1B31") ~ "katuko",
    str_detect(.$Filename, "M1B32") ~ "ratukus",
    str_detect(.$Filename, "M1B33") ~ "cepelino",
    str_detect(.$Filename, "M1B34") ~ "tylumus",
    str_detect(.$Filename, "M1B36") ~ "gynimo",
    str_detect(.$Filename, "M1B37") ~ "cepelinus",
    str_detect(.$Filename, "M1B38") ~ "ridiko",
    str_detect(.$Filename, "M1B39") ~ "gynimus",
    str_detect(.$Filename, "M1B40") ~ "paketo",
    str_detect(.$Filename, "M1B41") ~ "ridike",
    str_detect(.$Filename, "M1B43") ~ "senumus",
    str_detect(.$Filename, "M1B44") ~ "palikime",
    str_detect(.$Filename, "M1B45") ~ "kalakutas",
    str_detect(.$Filename, "M1B46") ~ "malonumus",
    str_detect(.$Filename, "M1B47") ~ "tylumas",
    str_detect(.$Filename, "M1B48") ~ "kalakuto",
    str_detect(.$Filename, "M1B50") ~ "palikimus",
    str_detect(.$Filename, "M1B51") ~ "remimas",
    str_detect(.$Filename, "M1B52") ~ "cepelinas",
    str_detect(.$Filename, "M1B53") ~ "gynime",
    str_detect(.$Filename, "M1B54") ~ "palikimo",
    str_detect(.$Filename, "M1B55") ~ "tylume",
    str_detect(.$Filename, "M1B56") ~ "mygtuko",
    str_detect(.$Filename, "M1B58") ~ "palikimas",
    str_detect(.$Filename, "M1B59") ~ "kalakute",
    str_detect(.$Filename, "M1B61") ~ "tylumo",
    str_detect(.$Filename, "M1B62") ~ "malonumas",
    str_detect(.$Filename, "M1B63") ~ "lupike",
    str_detect(.$Filename, "M1B65") ~ "deguto",
    str_detect(.$Filename, "M1B66") ~ "malonume",
    str_detect(.$Filename, "M1B67") ~ "senumo",
    str_detect(.$Filename, "M1B68") ~ "mygtukas",
    str_detect(.$Filename, "M1B69") ~ "remimo",
    str_detect(.$Filename, "M1B70") ~ "apetite",
    str_detect(.$Filename, "M1B72") ~ "gynimas",
    str_detect(.$Filename, "M1B73") ~ "remime",
    str_detect(.$Filename, "M1B74") ~ "malonumo",
    str_detect(.$Filename, "M1B75") ~ "degutas",
    str_detect(.$Filename, "M1B76") ~ "kalokutus",
    str_detect(.$Filename, "M1B77") ~ "senumas",
    str_detect(.$Filename, "M1B78") ~ "ratuke",
    str_detect(.$Filename, "M1C6") ~ "remimas",
    str_detect(.$Filename, "M1C7") ~ "lupiko",
    str_detect(.$Filename, "M1C9") ~ "deguto",
    str_detect(.$Filename, "M1C10") ~ "paketus",
    str_detect(.$Filename, "M1C11") ~ "remime",
    str_detect(.$Filename, "M1C12") ~ "tylumus",
    str_detect(.$Filename, "M1C14") ~ "gynimo",
    str_detect(.$Filename, "M1C15") ~ "paketas",
    str_detect(.$Filename, "M1C16") ~ "palikimus",
    str_detect(.$Filename, "M1C17") ~ "tylumas",
    str_detect(.$Filename, "M1C18") ~ "ratukus",
    str_detect(.$Filename, "M1C19") ~ "paketo",
    str_detect(.$Filename, "M1C20") ~ "apetite",
    str_detect(.$Filename, "M1C22") ~ "palikimas",
    str_detect(.$Filename, "M1C23") ~ "ratuko",
    str_detect(.$Filename, "M1C24") ~ "lupikas",
    str_detect(.$Filename, "M1C25") ~ "tylumo",
    str_detect(.$Filename, "M1C26") ~ "mygtuke",
    str_detect(.$Filename, "M1C27") ~ "senumo",
    str_detect(.$Filename, "M1C29") ~ "pakete",
    str_detect(.$Filename, "M1C30") ~ "remimo",
    str_detect(.$Filename, "M1C31") ~ "malonumas",
    str_detect(.$Filename, "M1C32") ~ "kalakutus",
    str_detect(.$Filename, "M1C33") ~ "cepelinas",
    str_detect(.$Filename, "M1C34") ~ "lupike",
    str_detect(.$Filename, "M1C36") ~ "apetitus",
    str_detect(.$Filename, "M1C37") ~ "gynimas",
    str_detect(.$Filename, "M1C38") ~ "malonumus",
    str_detect(.$Filename, "M1C39") ~ "senumas",
    str_detect(.$Filename, "M1C40") ~ "degute",
    str_detect(.$Filename, "M1C41") ~ "mygtukus",
    str_detect(.$Filename, "M1C43") ~ "cepelinus",
    str_detect(.$Filename, "M1C44") ~ "apetito",
    str_detect(.$Filename, "M1C45") ~ "degutas",
    str_detect(.$Filename, "M1C46") ~ "ridike",
    str_detect(.$Filename, "M1C47") ~ "remimus",
    str_detect(.$Filename, "M1C48") ~ "cepeline",
    str_detect(.$Filename, "M1C50") ~ "ratuke",
    str_detect(.$Filename, "M1C51") ~ "katuko",
    str_detect(.$Filename, "M1C52") ~ "lupikus",
    str_detect(.$Filename, "M1C53") ~ "palikimo",
    str_detect(.$Filename, "M1C54") ~ "gynimus",
    str_detect(.$Filename, "M1C55") ~ "apetitas",
    str_detect(.$Filename, "M1C56") ~ "degutus",
    str_detect(.$Filename, "M1C58") ~ "cepelino",
    str_detect(.$Filename, "M1C59") ~ "senume",
    str_detect(.$Filename, "M1C60") ~ "ridikas",
    str_detect(.$Filename, "M1C61") ~ "katukus",
    str_detect(.$Filename, "M1C62") ~ "gynime",
    str_detect(.$Filename, "M1C63") ~ "senumus",
    str_detect(.$Filename, "M1C65") ~ "kalakute",
    str_detect(.$Filename, "M1C66") ~ "malonumo",
    str_detect(.$Filename, "M1C67") ~ "mygtukas",
    str_detect(.$Filename, "M1C68") ~ "ratukas",
    str_detect(.$Filename, "M1C69") ~ "tylume",
    str_detect(.$Filename, "M1C70") ~ "katukas",
    str_detect(.$Filename, "M1C72") ~ "kalakuto",
    str_detect(.$Filename, "M1C75") ~ "katuke",
    str_detect(.$Filename, "M1C76") ~ "kalakutas",
    str_detect(.$Filename, "M1C77") ~ "ridiko"
  )) %>%
  mutate(., Segment = case_when(                                               #step 8
    str_detect(.$Filename, "M1A6") ~ "R",
    str_detect(.$Filename, "M1A7") ~ "R",
    str_detect(.$Filename, "M1A8") ~ "R",
    str_detect(.$Filename, "M1A9") ~ "O",
    str_detect(.$Filename, "M1A10") ~ "O",
    str_detect(.$Filename, "M1A11") ~ "R",
    str_detect(.$Filename, "M1A12") ~ "O",
    str_detect(.$Filename, "M1A14") ~ "O",
    str_detect(.$Filename, "M1A15") ~ "R",
    str_detect(.$Filename, "M1A16") ~ "O",
    str_detect(.$Filename, "M1A17") ~ "O",
    str_detect(.$Filename, "M1A18") ~ "O",
    str_detect(.$Filename, "M1A19") ~ "O",
    str_detect(.$Filename, "M1A20") ~ "R",
    str_detect(.$Filename, "M1A22") ~ "O",
    str_detect(.$Filename, "M1A23") ~ "O",
    str_detect(.$Filename, "M1A24") ~ "O",
    str_detect(.$Filename, "M1A25") ~ "O",
    str_detect(.$Filename, "M1A26") ~ "R",
    str_detect(.$Filename, "M1A27") ~ "R",
    str_detect(.$Filename, "M1A29") ~ "R",
    str_detect(.$Filename, "M1A30") ~ "O",
    str_detect(.$Filename, "M1A31") ~ "O",
    str_detect(.$Filename, "M1A32") ~ "O",
    str_detect(.$Filename, "M1A33") ~ "R",
    str_detect(.$Filename, "M1A34") ~ "O",
    str_detect(.$Filename, "M1A36") ~ "R",
    str_detect(.$Filename, "M1A37") ~ "R",
    str_detect(.$Filename, "M1A38") ~ "O",
    str_detect(.$Filename, "M1A39") ~ "R",
    str_detect(.$Filename, "M1A40") ~ "R",
    str_detect(.$Filename, "M1A41") ~ "O",
    str_detect(.$Filename, "M1A43") ~ "R",
    str_detect(.$Filename, "M1A44") ~ "R",
    str_detect(.$Filename, "M1A45") ~ "R",
    str_detect(.$Filename, "M1A46") ~ "O",
    str_detect(.$Filename, "M1A47") ~ "O",
    str_detect(.$Filename, "M1A48") ~ "R",
    str_detect(.$Filename, "M1A51") ~ "R",
    str_detect(.$Filename, "M1A52") ~ "R",
    str_detect(.$Filename, "M1A53") ~ "O",
    str_detect(.$Filename, "M1A54") ~ "O",
    str_detect(.$Filename, "M1A55") ~ "R",
    str_detect(.$Filename, "M1A56") ~ "O",
    str_detect(.$Filename, "M1A58") ~ "O",
    str_detect(.$Filename, "M1A59") ~ "O",
    str_detect(.$Filename, "M1A60") ~ "R",
    str_detect(.$Filename, "M1A61") ~ "R",
    str_detect(.$Filename, "M1A62") ~ "R",
    str_detect(.$Filename, "M1A63") ~ "O",
    str_detect(.$Filename, "M1A65") ~ "R",
    str_detect(.$Filename, "M1A66") ~ "O",
    str_detect(.$Filename, "M1A67") ~ "O",
    str_detect(.$Filename, "M1A68") ~ "O",
    str_detect(.$Filename, "M1A69") ~ "O",
    str_detect(.$Filename, "M1A70") ~ "R",
    str_detect(.$Filename, "M1A72") ~ "R",
    str_detect(.$Filename, "M1A73") ~ "O",
    str_detect(.$Filename, "M1A74") ~ "O",
    str_detect(.$Filename, "M1A75") ~ "O",
    str_detect(.$Filename, "M1A76") ~ "R",
    str_detect(.$Filename, "M1A77") ~ "O",
    str_detect(.$Filename, "M1A78") ~ "R",
    str_detect(.$Filename, "M1B6") ~ "O",
    str_detect(.$Filename, "M1B7") ~ "O",
    str_detect(.$Filename, "M1B8") ~ "O",
    str_detect(.$Filename, "M1B10") ~ "R",
    str_detect(.$Filename, "M1B11") ~ "O",
    str_detect(.$Filename, "M1B14") ~ "R",
    str_detect(.$Filename, "M1B15") ~ "O",
    str_detect(.$Filename, "M1B16") ~ "O",
    str_detect(.$Filename, "M1B17") ~ "O",
    str_detect(.$Filename, "M1B18") ~ "O",
    str_detect(.$Filename, "M1B19") ~ "O",
    str_detect(.$Filename, "M1B20") ~ "O",
    str_detect(.$Filename, "M1B23") ~ "O",
    str_detect(.$Filename, "M1B24") ~ "O",
    str_detect(.$Filename, "M1B25") ~ "O",
    str_detect(.$Filename, "M1B26") ~ "O",
    str_detect(.$Filename, "M1B27") ~ "O",
    str_detect(.$Filename, "M1B29") ~ "O",
    str_detect(.$Filename, "M1B30") ~ "O",
    str_detect(.$Filename, "M1B31") ~ "O",
    str_detect(.$Filename, "M1B32") ~ "O",
    str_detect(.$Filename, "M1B33") ~ "R",
    str_detect(.$Filename, "M1B34") ~ "R",
    str_detect(.$Filename, "M1B36") ~ "R",
    str_detect(.$Filename, "M1B37") ~ "R",
    str_detect(.$Filename, "M1B38") ~ "O",
    str_detect(.$Filename, "M1B39") ~ "R",
    str_detect(.$Filename, "M1B40") ~ "O",
    str_detect(.$Filename, "M1B41") ~ "O",
    str_detect(.$Filename, "M1B43") ~ "R",
    str_detect(.$Filename, "M1B44") ~ "R",
    str_detect(.$Filename, "M1B45") ~ "O",
    str_detect(.$Filename, "M1B46") ~ "R",
    str_detect(.$Filename, "M1B47") ~ "R",
    str_detect(.$Filename, "M1B48") ~ "O",
    str_detect(.$Filename, "M1B50") ~ "R",
    str_detect(.$Filename, "M1B51") ~ "R",
    str_detect(.$Filename, "M1B52") ~ "R",
    str_detect(.$Filename, "M1B53") ~ "R",
    str_detect(.$Filename, "M1B54") ~ "R",
    str_detect(.$Filename, "M1B55") ~ "R",
    str_detect(.$Filename, "M1B56") ~ "O",
    str_detect(.$Filename, "M1B58") ~ "R",
    str_detect(.$Filename, "M1B59") ~ "O",
    str_detect(.$Filename, "M1B61") ~ "R",
    str_detect(.$Filename, "M1B62") ~ "R",
    str_detect(.$Filename, "M1B63") ~ "O",
    str_detect(.$Filename, "M1B65") ~ "O",
    str_detect(.$Filename, "M1B66") ~ "R",
    str_detect(.$Filename, "M1B67") ~ "R",
    str_detect(.$Filename, "M1B68") ~ "O",
    str_detect(.$Filename, "M1B69") ~ "R",
    str_detect(.$Filename, "M1B70") ~ "O",
    str_detect(.$Filename, "M1B72") ~ "R",
    str_detect(.$Filename, "M1B73") ~ "R",
    str_detect(.$Filename, "M1B74") ~ "R",
    str_detect(.$Filename, "M1B75") ~ "O",
    str_detect(.$Filename, "M1B76") ~ "O",
    str_detect(.$Filename, "M1B77") ~ "R",
    str_detect(.$Filename, "M1B78") ~ "O",
    str_detect(.$Filename, "M1C6") ~ "R",
    str_detect(.$Filename, "M1C7") ~ "O",
    str_detect(.$Filename, "M1C9") ~ "O",
    str_detect(.$Filename, "M1C10") ~ "O",
    str_detect(.$Filename, "M1C11") ~ "R",
    str_detect(.$Filename, "M1C12") ~ "R",
    str_detect(.$Filename, "M1C14") ~ "R",
    str_detect(.$Filename, "M1C15") ~ "O",
    str_detect(.$Filename, "M1C16") ~ "R",
    str_detect(.$Filename, "M1C17") ~ "R",
    str_detect(.$Filename, "M1C18") ~ "O",
    str_detect(.$Filename, "M1C19") ~ "O",
    str_detect(.$Filename, "M1C20") ~ "O",
    str_detect(.$Filename, "M1C22") ~ "R",
    str_detect(.$Filename, "M1C23") ~ "O",
    str_detect(.$Filename, "M1C24") ~ "O",
    str_detect(.$Filename, "M1C25") ~ "R",
    str_detect(.$Filename, "M1C26") ~ "O",
    str_detect(.$Filename, "M1C27") ~ "R",
    str_detect(.$Filename, "M1C29") ~ "O",
    str_detect(.$Filename, "M1C30") ~ "R",
    str_detect(.$Filename, "M1C31") ~ "R",
    str_detect(.$Filename, "M1C32") ~ "O",
    str_detect(.$Filename, "M1C33") ~ "R",
    str_detect(.$Filename, "M1C34") ~ "O",
    str_detect(.$Filename, "M1C36") ~ "O",
    str_detect(.$Filename, "M1C37") ~ "R",
    str_detect(.$Filename, "M1C38") ~ "R",
    str_detect(.$Filename, "M1C39") ~ "R",
    str_detect(.$Filename, "M1C40") ~ "O",
    str_detect(.$Filename, "M1C41") ~ "O",
    str_detect(.$Filename, "M1C43") ~ "R",
    str_detect(.$Filename, "M1C44") ~ "O",
    str_detect(.$Filename, "M1C45") ~ "O",
    str_detect(.$Filename, "M1C46") ~ "O",
    str_detect(.$Filename, "M1C47") ~ "R",
    str_detect(.$Filename, "M1C48") ~ "R",
    str_detect(.$Filename, "M1C50") ~ "O",
    str_detect(.$Filename, "M1C51") ~ "O",
    str_detect(.$Filename, "M1C52") ~ "O",
    str_detect(.$Filename, "M1C53") ~ "R",
    str_detect(.$Filename, "M1C54") ~ "R",
    str_detect(.$Filename, "M1C55") ~ "O",
    str_detect(.$Filename, "M1C56") ~ "O",
    str_detect(.$Filename, "M1C58") ~ "R",
    str_detect(.$Filename, "M1C59") ~ "R",
    str_detect(.$Filename, "M1C60") ~ "O",
    str_detect(.$Filename, "M1C61") ~ "O",
    str_detect(.$Filename, "M1C62") ~ "R",
    str_detect(.$Filename, "M1C63") ~ "R",
    str_detect(.$Filename, "M1C65") ~ "O",
    str_detect(.$Filename, "M1C66") ~ "R",
    str_detect(.$Filename, "M1C67") ~ "O",
    str_detect(.$Filename, "M1C68") ~ "O",
    str_detect(.$Filename, "M1C69") ~ "R",
    str_detect(.$Filename, "M1C70") ~ "O",
    str_detect(.$Filename, "M1C72") ~ "O",
    str_detect(.$Filename, "M1C75") ~ "O",
    str_detect(.$Filename, "M1C76") ~ "O",
    str_detect(.$Filename, "M1C77") ~ "O"
  )) %>%
  mutate(., Frame = case_when(                                                 #step 9
    str_detect(.$TextGridLabel, "1$") ~ "1",
    str_detect(.$TextGridLabel, "10$") ~ "1",
    str_detect(.$TextGridLabel, "2$") ~ "1",
    str_detect(.$TextGridLabel, "20$") ~ "1",
    str_detect(.$TextGridLabel, "3$") ~ "1",
    str_detect(.$TextGridLabel, "30$") ~ "1",
    str_detect(.$TextGridLabel, "00$") ~ "2",
    str_detect(.$TextGridLabel, "4$") ~ "2",
    str_detect(.$TextGridLabel, "40$") ~ "2",
    str_detect(.$TextGridLabel, "5$") ~ "2",
    str_detect(.$TextGridLabel, "50$") ~ "2",
    str_detect(.$TextGridLabel, "6$") ~ "2",
    str_detect(.$TextGridLabel, "60$") ~ "2",
    str_detect(.$TextGridLabel, "0$") ~ "1"
  )) %>%
  mutate(., Syllnum = case_when(                                               #step 10
    str_detect(.$TextGridLabel, "1$") ~ "three",
    str_detect(.$TextGridLabel, "10$") ~ "four",
    str_detect(.$TextGridLabel, "2$") ~ "three",
    str_detect(.$TextGridLabel, "20$") ~ "four",
    str_detect(.$TextGridLabel, "3$") ~ "three",
    str_detect(.$TextGridLabel, "30$") ~ "four",
    str_detect(.$TextGridLabel, "00$") ~ "four",
    str_detect(.$TextGridLabel, "4$") ~ "three",
    str_detect(.$TextGridLabel, "40$") ~ "four",
    str_detect(.$TextGridLabel, "5$") ~ "three",
    str_detect(.$TextGridLabel, "50$") ~ "four",
    str_detect(.$TextGridLabel, "6$") ~ "three",
    str_detect(.$TextGridLabel, "60$") ~ "four",
    str_detect(.$TextGridLabel, "0$") ~ "four"
  )) %>%
  mutate(., f0_midpoint = as.double(f0_midpoint))                              #step 11


#remove the fixed point data from the intensity dataframe

data_intensity <- data2 %>%
  filter(., TextGridLabel != "fix1", TextGridLabel != "fix2") %>%
  select(., Intensity)


#combine the two dataframes using bind_cols

data_final2 <- bind_cols(data_final, data_intensity)

#save the dataframe as a new .csv file in the data_clean folder

write_csv(data_final2, "./data_clean/data_clean.csv")
